# Generated by Django 4.1.6 on 2023-02-12 07:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ExamInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('descr', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=200, verbose_name='Почта')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HigherEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Высшее образование')),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('position', models.CharField(max_length=200, verbose_name='Позиция')),
            ],
        ),
        migrations.CreateModel(
            name='SingletonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cпециализация')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка видеролика')),
            ],
        ),
        migrations.CreateModel(
            name='preparingFoExam',
            fields=[
                ('singletonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.singletonmodel')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='images')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('descr', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('sub_title_two', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('descr_two', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            bases=('applications.singletonmodel',),
        ),
        migrations.CreateModel(
            name='SingletonModelAboutUs',
            fields=[
                ('singletonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.singletonmodel')),
                ('img', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('descr', models.TextField(verbose_name='Описание')),
            ],
            bases=('applications.singletonmodel',),
        ),
        migrations.CreateModel(
            name='SingletonModelAdvantage',
            fields=[
                ('singletonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.singletonmodel')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('descr', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='images')),
            ],
            bases=('applications.singletonmodel',),
        ),
        migrations.CreateModel(
            name='SingletonModelContactInfo',
            fields=[
                ('singletonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.singletonmodel')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=200, verbose_name='Почта')),
                ('telegram', models.CharField(max_length=200, verbose_name='Ссылка телеграма')),
                ('whatsapp', models.CharField(max_length=200, verbose_name='Ссылка whatsapp')),
                ('instagram', models.CharField(max_length=200, verbose_name='Ссылка instagram')),
                ('youtube', models.CharField(max_length=200, verbose_name='Ссылка youtube')),
            ],
            bases=('applications.singletonmodel',),
        ),
        migrations.CreateModel(
            name='SingletonModelExam',
            fields=[
                ('singletonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.singletonmodel')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('descr', models.TextField(verbose_name='Описание')),
            ],
            bases=('applications.singletonmodel',),
        ),
        migrations.CreateModel(
            name='SingletonModelExamInf',
            fields=[
                ('singletonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.singletonmodel')),
                ('img', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('descr', models.TextField(verbose_name='Описание')),
            ],
            bases=('applications.singletonmodel',),
        ),
        migrations.CreateModel(
            name='SingletonModelStudyAbroad',
            fields=[
                ('singletonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.singletonmodel')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='images')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('descr', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            bases=('applications.singletonmodel',),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположения')),
                ('DateOfFoundation', models.IntegerField(verbose_name='Дата основания')),
                ('TypeOfPrograms', models.CharField(max_length=200, verbose_name='Тип Программы')),
                ('age', models.IntegerField()),
                ('language', models.CharField(max_length=200, verbose_name='Языки')),
                ('Cost', ckeditor.fields.RichTextField(verbose_name='Стоимость')),
                ('icon', models.FileField(upload_to='images')),
                ('fac_university', models.CharField(max_length=200)),
                ('NominalDuration', models.CharField(max_length=200, verbose_name='Номинальная продолжительность')),
                ('Awards', models.CharField(max_length=200, verbose_name='Награды')),
                ('TuitionFee', models.CharField(max_length=200, verbose_name='Плата за обучение')),
                ('ApplicationFee', models.CharField(max_length=200, verbose_name='Плата за подачу заявления')),
                ('RegistrationFee', models.CharField(max_length=200, verbose_name='Регистрационный сбор')),
                ('EntryQualication', models.CharField(max_length=200, verbose_name='Вступление Квалификация')),
                ('Pre_deadline', models.CharField(max_length=200, verbose_name='До дедлайна')),
                ('ApplicationDeadline', models.CharField(max_length=200, verbose_name='Срок подачи заявки')),
                ('StudiesCommence', models.CharField(max_length=200, verbose_name='Учеба Начало')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.country')),
            ],
        ),
        migrations.CreateModel(
            name='UnerversityGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.university')),
            ],
        ),
    ]
